defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/openjdk:8-jdk
  environment:
    MAVEN_OPTS: -Xmx3200m

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: mvn clean install
      - run: bash <(curl -s https://codecov.io/bash)

  unit-tests:
    <<: *defaults
    steps:
      - checkout
      - run: mvn test -Dgroups="categories.UnitTest"

  integration-tests:
    <<: *defaults
    steps:
      - checkout
      - run: mvn test -Dgroups="categories.IntegrationTest"

workflows:
  version: 2
  build_and_tests:
    jobs:
      - build
      - unit-tests
      - integration-tests:
          requires:
            - build
