defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/openjdk:8-jdk
  environment:
    MAVEN_OPTS: -Xmx3200m
    EUREKA_URL: https://eureka-i3a.herokuapp.com/eureka/

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: wget https://github.com/Arquisoft/Agents_i3a/archive/v0.1.zip
      - run: unzip v0.1.zip
      - run: wget https://github.com/thewilly/UDocs/raw/master/kafka_2.11-0.11.0.1.zip -O kafka.zip
      - run: mkdir -p kafka && unzip kafka.zip
      - run:
          command: sh kafka_2.11-0.11.0.1/bin/zookeeper-server-start.sh kafka_2.11-0.11.0.1/config/zookeeper.properties;
          background: true
      - run:
          command: sh kafka_2.11-0.11.0.1/bin/kafka-server-start.sh kafka_2.11-0.11.0.1/config/server.properties;
          background: true
      - run:
          command: cd Agents_i3a-0.1/; mvn spring-boot:run;
          background: true
      - run: sleep 30; sh kafka_2.11-0.11.0.1/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic INCIDENCES;
      - run: sleep 120; mvn clean install
      - run: bash <(curl -s https://codecov.io/bash)

  unit-tests:
    <<: *defaults
    steps:
      - checkout
      - run: mvn test -Dgroups="TestKit.UnitTest";

  integration-tests:
    <<: *defaults
    steps:
      - checkout
      - run: wget https://github.com/Arquisoft/Agents_i3a/archive/v0.1.zip
      - run: unzip v0.1.zip
      - run: wget https://github.com/thewilly/UDocs/raw/master/kafka_2.11-0.11.0.1.zip -O kafka.zip
      - run: mkdir -p kafka && unzip kafka.zip
      - run:
          command: sh kafka_2.11-0.11.0.1/bin/zookeeper-server-start.sh kafka_2.11-0.11.0.1/config/zookeeper.properties;
          background: true
      - run:
          command: sh kafka_2.11-0.11.0.1/bin/kafka-server-start.sh kafka_2.11-0.11.0.1/config/server.properties
          background: true
      - run:
          command: cd Agents_i3a-0.1/; mvn spring-boot:run;
          background: true
      - run: sleep 30; sh kafka_2.11-0.11.0.1/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic INCIDENCES;
      - run: sleep 120; mvn test -Dgroups="TestKit.IntegrationTest";

workflows:
  version: 2
  build_and_tests:
    jobs:
      - build
      - unit-tests
      - integration-tests:
          requires:
            - build
